### ISSUE TITLE
GPO wishes: "more bookmarks", "bookmarks cleanup" and "what GPO is applied?"

### ISSUE THREAD

**Issue by SwissJay** [mozilla/policy-templates#126]
GPOs are working great, but I miss 3 things:
1) a way to push more than 5 bookmarks via GPO,
2) a way to completely clear all bookmarks before applying the list from 1) (we have student lab PCs that are showing tons of duplicate bookmarks, not sure why, but no automated way to clean them out),
3) a hint in the GUI (possibly on the "Help - About" screen) that would show which GPO is being applied. We have 3 different flavors here: student, staff, IT and CCK allowed me to display which one was applied, but can't find such an option with the GPOs.

Many thanks and keep up the good work!!

**Comment by mkaply** [comment]
> a way to push more than 5 bookmarks via GPO,

I'll add a few more. Would 10 be enough?

> a way to completely clear all bookmarks before applying the list from 1) (we have student lab PCs that are showing tons of duplicate bookmarks, not sure why, but no automated way to clean them out),

Do you mean ALL bookmarks?

> a hint in the GUI (possibly on the "Help - About" screen) that would show which GPO is being applied. We have 3 different flavors here: student, staff, IT and CCK allowed me to display which one was applied, but can't find such an option with the GPOs.

We're planning to add an about:policies page. Didn't make this version.

**Comment by Buenno** [comment]
@SwissJay You can also add more bookmarks yourself by editing the ADMX and ADML files, then copying these edited files to you central store, I have done just this. Just search the ADMX file for "bookmark1" and you should be able to figure out how the file is constructed, you just need to copy and paste the policy and edit the bookmark number from bookmark1 to say, bookmark6. 

You also need to do something similar in the ADML file, search that for the same string and copy, paste and replace.  Save and deploy.

@mkaply As with CCK, I've not been able to figure out how to add subfolders to the bookmarks toolbar. I want something along the lines of 'Folder1\Folder2\Bookmark1'. Is this supported? If so, how do I achieve this result? 

Apologies for commenting this here, but I figured the issue was related.

**Comment by mkaply** [comment]
FYI, in the next version of Firefox, you'll be able to go to about:policies to see what policies are applied.

**Comment by jeffreymcclain** [comment]
@mkaply will "about:policies" be added to the ESR branch in the near future? Or will it not be included until the next major ESR release in September 2019?

**Comment by mkaply** [comment]
Unfortunately because about:policies involved translation, we couldn't add it to the ESR.

**Comment by MichaelHuke** [comment]
I  just came across the duplicates problem:
Each time I start Firfox, the bookmarks are added via GPO again, even if they are already there. After some time I have many copies ofm each bookmark
What can I do, to limit them to be added just once?

thanx, Michael

**Comment by mkaply** [comment]
I've added a new policy that does a better job of bookmarks.

I would recommend using it instead.

https://github.com/mozilla/policy-templates/blob/master/README.md#managedbookmarks

I believe the other issues have been solved.
