### ISSUE TITLE
GPO : Problem with Default custom search engine

### ISSUE THREAD

**Issue by redm5** [mozilla/policy-templates#147]
Hello,

i tried to define a default custom engine which i created with the group policies but it's not working. The custom search engine exists but i need to select it manually in the browser options.

Is there anything special to do ?

thanks for your help.

**Comment by HeiHei90** [comment]
I've got a related problem.
Via GPO I create a custom search engine and set it as default search engine. 
But it has no effect on my FireFox 60.0.2 ESR (It once worked, quite at the first ADMX-Version with a Beta of FF60).

When I open the browser-console with browser.policies.loglevel debug it looks smth like this (which seems ok to me):

...
"SearchEngines": {
    "Default": "CustomSearchName",
    "PreventInstalls": 1,
    "Add": [
        {
            "Name": "CustomSearchName",
            "URLTemplate": "https://search.company.com/Pages/results.aspx?k={searchTerms}",
            "Method": "GET",
            "IconURL": "",
            "Alias": "",
            "Description": "Best internal search ever",
            "SuggestURLTemplate": ""
        }
    ]
...

Validation seems to be fine.
But then:
Policies.jsm: Not running action addSearchEngines again because the policy's value is unchanged
Policies.jsm: Not running action setDefaultSearchEngine again because it has already run.

Custom Search engine is not available in FireFox nor set to default.

Is this a Bug?
Any ideas?

**Comment by mkaply** [comment]
@HeiHei90 What's happening is that we believe the policy has already been set so we are not setting it again.

Go to about:config and search on "addSearchEngines" and "setDefaultEngines"
Right click and reset those two preferences and see if that fixes things.

**Comment by redm5** [comment]
I found a solution by setting the 

browser.policies.runonce.setDefaultSearchEngine

value in about:config to false.

I assume that like this the default search engine is set on every firefox launch.

have fun :P

**Comment by HeiHei90** [comment]
@mkaply allright, I did as you mentioned. 

Now I get an Error:

NS_ERROR_FAILURE: new EngineURL: template is not a valid URI!
Policies.jsm: Unable to add search engine Exception { name: "NS_ERROR_FAILURE", message: "new EngineURL: template is not a va...", result ...... 

But "URLTemplate": "https://search.company.com/Pages/results.aspx?k={searchTerms}" is correct or isn't it?
Is this error because I did not define a "Suggest Url Template"? Is this one mandatory?

Thanks

**Comment by redm5** [comment]
Maybe try this for the URLTemplate 

https://search.company.com/search?q={searchTerms}

or this

https://search.company.com/Pages/results.aspx?q={searchTerms}



I think the template depends on each company which mades the search engine itself... and for the suggest part i think that it is not mandatory.

**Comment by HeiHei90** [comment]
Ok, I tried it with another URL. Same reult. Same error. 

ADMX: newest
FireFox: 60.0.2 ESR

Is the URI validation broken? It is correct, that we have to place {SearchTerms} into the URI, right?

**Comment by mkaply** [comment]
Yes, you do have to place {SearchTerms} in, and that URL is valid. Is there possible a space at the beginning or end?

Could you export the registry entry so I can look at it?

**Comment by HeiHei90** [comment]
Thank you for your response. Luckily I'm out of work for today. I will check your proposes tomorrow, as soon as I'm back in the office! 

Thank you.

**Comment by HeiHei90** [comment]
Dear @mkaply, I've send you the requested information to your E-Mail-Address. 
I hope this is ok. Don't want to spam this thread any further. 
Subject of the Mail: 
mozilla/policy-templates "GPO : Problem with Default custom search engine #147"

**Comment by mkaply** [comment]
@redm5 Yes, that policy is not designed to do the default engine at every startup.

We found @HeiHei90's problem via email. suggestionURL was in the template for some reason.
