### ISSUE TITLE
How could someone get involved?

### ISSUE THREAD

**Issue by scottnotpat** [mozilla/policy-templates#152]
Is there a way someone could help add additional settings to the ADMX files?

**Comment by mkaply** [comment]
When we make changes to Firefox, we do need them added to the ADMX files, so that is definitely one area where we can use help. We open new issues when we need them. Some other things we could use help on are:

Updating ADM files to use minimum version to mean Firefox version instead of Windows version.
Moving the documentation over to HTML.

**Comment by mkaply** [comment]
Appreciate the changes you made Scott. So we're ready for you to help  more if you are up for it.

I'm tracking the new policies we're adding here:

https://docs.google.com/spreadsheets/d/11z_GTMRnPwSxFxvvyAhGciHuTRifoU_r-tpvEpun2OM/edit#gid=0

With each of those new policies, we'll need to update the ADMX templates. The changes are usually pretty straightforward (mapping from the schema to the Windows registry). You can see an example here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1471651
https://github.com/mozilla/policy-templates/pull/180

**Comment by scottnotpat** [comment]
It will be another day or so before I can dig in. I am still interested.

Thanks!

=============================================
Scott Meyer
Sr. Network Systems Analyst
Des Moines Area Community College - Urban Campus
psmeyer@dmacc.edu<mailto:psmeyer@dmacc.edu>
515-248-7246
=============================================

**Comment by mkaply** [comment]
Feel free to do any cleanup/suggestions to the current ADMX files.
