### ISSUE TITLE
GPO wish: serviceWorkers and push

### ISSUE THREAD

**Issue by ppascher** [mozilla/policy-templates#175]
Currently `dom.serviceWorkers.enabled` and `dom.push.enabled` are disabled by default in Firefox 60 ESR. As this are two settings required to be enabled for various services we would like to enable them via GPO instead of falling back to autoconfig.

**Comment by mkaply** [comment]
Currently we don't uplift security patches for service workers to ESR and we  And we don't want to commit to supporting service workers on ESR because we're re-writing most of it.

As a result, using these is at your own risk, so you'll need to use Autoconfig. I am looking at whether or not we can specify an Autooconfig file via GPO which might help here.

**Comment by rosskoes05** [comment]
@mkaply - Is this still the case for ESR 68?

**Comment by mkaply** [comment]
Unfortunately yes.

See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1547023#c0
