### ISSUE TITLE
Error after install policy 1.1

### ISSUE THREAD

**Issue by Mephysto666** [mozilla/policy-templates#227]
Hi there,
I tried to install last version of windows policies but I get an error:

![immagine](https://user-images.githubusercontent.com/3337127/45139064-e0476000-b1ae-11e8-8c48-9fe6fc6b9fda.png)

I am sorry if it is in Italian language.

Kind regards.

**Comment by hheinen** [comment]
Hi @Mephysto666 , can you translate that in english? I get an error, too. And I want to clarify if it is the same.

**Comment by Mephysto666** [comment]
Hi @hheinen, I try to translate:

The '$(string.Bookmark01)' resource that is referenced in the displayName attribute can not be found.
File C:\Windows\PolicyDefinitions\firefox.admx, row 771, column 212

I am sorry for my english.

Bye.

Meph

**Comment by hheinen** [comment]
Thank you. I just used google translate^^:

The resource '$(string.Bookmark01)' referenced in the displayName attribute could not be found.
...

Ok, I guess I found the error.
In firefox.admx is a reference to '$string.Bookmark01' but in the italian translation file (it-IT/firefox.adml) there it is named 'Bookmark1' instead of 01 just 1. 

I'll create an pull request, where the error should be fixed.
For so long, You could manually change the it-IT/firefox.adml starting at line 348 till 352 and adding a 0 in front of the single number.

Greetings from germany

**Comment by hheinen** [comment]
@Mephysto666  could you please try and tell me if that fix your problem?

**Comment by MichaelScheler** [comment]
same in the de-DE version...

**Comment by hheinen** [comment]
@MichaelScheler jeb. Could you verify if my solution would fix the problem?

**Comment by MichaelScheler** [comment]
jep, fixed for Bookmark 01 to 05.
Next Problem is EN has 50 bookmarks configured, DE and IT only 5, so we get errors from 06 onwards.

**Comment by hheinen** [comment]
Meh, ok. I can fix that problem too, but only for the german version.

**Comment by MichaelScheler** [comment]
I just copied the bookmarks 6 to 50 from the EN to DE version (without translating) - problem solved.

**Comment by Mephysto666** [comment]
@hheinen your suggestion worked done, but I had to add this row

`<string id="Bookmark06">Segnalibro 6</string>`

at line 353 of italian firefox.adml.

**Comment by hheinen** [comment]
Created a pull request that fixes the problem of the missing leading 0.
Added bookmark-strings for german and italian up to 50.

**Comment by mkaply** [comment]
I've updated the ZIP file here:

https://github.com/mozilla/policy-templates/releases/tag/v1.1

to include this fix.
