### ISSUE TITLE
Availability of certificate policy on Linux

### ISSUE THREAD

**Issue by gcorsini** [mozilla/policy-templates#282]
Using one file to manage all policies is awesome! In my environment, there are Windows and Linux machines and ideally, there should only be one policies.json file.
Do you have any idea about when the [certificate policy](https://github.com/mozilla/policy-templates#certificates) will be available on Linux?

**Comment by gcorsini** [comment]
Certificate policy also works on Linux! Sorry, I looked for the wrong certificate name. Everything is fine and this feature is awesome. Thank you very much!

**Comment by mkaply** [comment]
I'm going to be allowing the policy file to be in the etc directory on Linux. That should solve this.

**Comment by bplainia** [comment]
I also have a windows/linux environment and having firefox use system certificates on Linux would allow us to upgrade to a newer version of Firefox.

For Ubuntu, Firefox would just need to look at `/etc/ssl/certs/ca-certificates.crt` if ca-certificates is installed . On OpenSUSE, you would look at `/var/lib/ca-certificates/ca-bundle.pem`

**Comment by mkaply** [comment]
So maybe I should allow fully qualified paths for the cert location in addition to file names.

Then you could just specify the path to the cert?

**Comment by gcorsini** [comment]
I think the cleanest solution would be the ability to specify the location of the certificate store using a fully qualified path. (Then sysadmins would only have to install new certs/CA to the certificate store they specified.)
Alternatively, it would also be a solution to have a list of fully qualified paths to the certificates that should be added to Firefox. (A list would make more sense in my opinion as sysadmins might install multiple certs.)

**Comment by tresf** [comment]
Wanted to add my experiences here... I'm testing Firefox 64 on Ubuntu 18.04 (provided by `apt`) and neither the fully qualified path nor the absolute path certs are working.  `about:policies` shows the certificate installed and the same certificate works through autoconfig, but I cannot get it to work.

My policy looks something like this:

```js
{
  "policies": {
    "Certificates": {
      "Install": [
        "my.crt",
        "/opt/myapp/my.crt"
      ]
    }
  }
}
```

The [policies documentation](https://github.com/mozilla/policy-templates/blob/master/README.md#certificates) has been updated to reflect the certificate installation logic (with a note about full paths being supported with the release of Firefox 65), but my tests on the Firefox 64 provided by Ubuntu are failing.

My main concern from an ISV perspective is that we'd like to bake the conditional `AutoConfig`/`policies.json` logic into our desktop installers now but need to know a Firefox version that is guaranteed to work with this new feature so that once it's made available we don't need to re-release our software for the sake of Firefox (we've disgruntledly done this in the past, but we prefer to get ahead of these things).

**Comment by tresf** [comment]
**Edit:** Relative paths ARE working in Firefox 64.   Post updated.

**Comment by tresf** [comment]
Firefox 65 was released today.  This new policy, as well as the absolute paths works great.  I [force-installed it on Ubuntu 18.04](https://forum.linuxconfig.org/t/how-to-install-uninstall-and-update-firefox-on-ubuntu-18-04-bionic-beaver-linux-linuxconfig-org/1698/2?u=tresf) using the tarball.

**Comment by mkaply** [comment]
This was fixed.
