### ISSUE TITLE
Allow unconfigured selective sanitize

### ISSUE THREAD

**Issue by mimi89999** [mozilla/policy-templates#488]
Hello,

It is not uncommon for enterprise deployments that store user data on a central and have roaming profiles to want to delete the browser cache when the browser is closed.

The problem is that I can't set `SanitizeOnShutdown\Cache` without leaving other `privacy.clearOnShutdown` options undefined. I have to set them to false. This in turn makes it impossible for users to enable them.

**Comment by mkaply** [comment]
I assume you're referring specifically to how the GPO works. I'll look at turning this into a category with each item underneath it so they can be enabled individually.

**Comment by mkaply** [comment]
So the core problem here is that in Firefox, clearing cache, downloads, formdata, history and sessions is the default. So when you turn on "clear data", those will automatically get cleared unless explicitly set to false.

So my workaround was to set things to false unless they are explicitly marked true.

Is the primary issue here that I don't provide a way to not lock the preferences? That would be easy to change.

(note there is a separate issue with the GPO - I plan to fix that as well. so that you can choose to not set the other ones. Note that if something like downloads isn't set, it will default to false unlike fierfox which defaults it to true)

**Comment by mkaply** [comment]
To be more clear, the policy code says things like "If they haven't asked for cookies to be cleared, set it to false because they probably don't want the Firefox default of clearing cookies"

**Comment by mimi89999** [comment]
> Is the primary issue here that I don't provide a way to not lock the preferences?

Yes. That's what I would like to do. I would also like to not clear them by default, unless the user enables them. I only want to enable and lock clearing the cache.

**Comment by mkaply** [comment]
FYI, I have a fix for this that will be in the next Firefox and the next ESR dot release

https://bugzilla.mozilla.org/show_bug.cgi?id=1613722

**Comment by mkaply** [comment]
Here's the way things work with the new policy.

Previously, these values were always locked. Starting with Firefox 74 and Firefox ESR 68.6, you can use the `Locked` option to either keep the values unlocked (set it to false), or lock only the values you set (set it to true). If you want the old behavior of locking everything, do not set `Locked` at all.

For GPO, I made everything a category so you can set one thing without affecting the others.

This should give you what you are looking for. I'm closing since all the code is checked in and will be released next week.
