### ISSUE TITLE
Clarify cookie settings

### ISSUE THREAD

**Issue by ghost** [mozilla/policy-templates#509]
Previously I set permissions like this:

~~~js
const o1 = Services.io.newURI('https://www.google.com');
Services.perms.add(o1, 'cookie', Ci.nsICookiePermission.ACCESS_DENY);
const o2 = Services.io.newURI('https://www.youtube.com');
Services.perms.add(o2, 'cookie', Ci.nsICookiePermission.ACCESS_SESSION);
~~~

However that doesnt work anymore:

https://bugzilla.mozilla.org/show_bug.cgi?id=1603979

So I was pointed here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1604107

Which points to here:

https://github.com/mozilla/policy-templates#policiesjson-10

Where I see this:

~~~js
{
  "policies": {
    "Cookies": {
      "Allow": ["http://example.org/"],
      "Block": ["http://example.edu/"],
      "Default": true | false,
      "AcceptThirdParty": "always" | "never" | "from-visited"],
      "ExpireAtSessionEnd": true | false,
      "RejectTracker": true | false,
      "Locked": true | false
    }
  }
}
~~~

However I have a couple of issue with this code. First this:

~~~js
"AcceptThirdParty": "always" | "never" | "from-visited"],
~~~

is a syntax error, as its missing open bracket. Secondly its not clear how my
settings would map to the new format. I think this is right:

~~~js
{
   "policies": {
      "Cookies": {
         "Block": ["https://www.google.com"],
         "Allow": ["https://www.youtube.com"],
         "ExpireAtSessionEnd": true,
      }
   }
}
~~~

Can someone confirm?

**Comment by mkaply** [comment]
We don't support ACCESS_SESSION. You're the first person I've ever seen using that permission attribute.

If you want to continue using what you have, it's a straightforward change. You can look at how to change .add here:

https://bugzilla.mozilla.org/show_bug.cgi?id=1574483

As far as your policy changes, it sets all cookies to expire at session end (which might not be what you want).

And I'll fix the typo.

**Comment by cup** [comment]
@mkaply I am not a Firefox expert, only a user.

The page you linked to has no code examples, can you clarify why you linked to it?

**Comment by mkaply** [comment]
Sorry, I assume that because you had:

const o1 = Services.io.newURI('https://www.google.com');
Services.perms.add(o1, 'cookie', Ci.nsICookiePermission.ACCESS_DENY);
const o2 = Services.io.newURI('https://www.youtube.com');
Services.perms.add(o2, 'cookie', Ci.nsICookiePermission.ACCESS_SESSION);


in your config, you would know where that came from. I was saying that equivalent version is now:

const o1 =         Services.scriptSecurityManager.createContentPrincipalFromOrigin('https://www.google.com');
Services.perms.addFromPrincipal(o1, 'cookie', Ci.nsICookiePermission.ACCESS_DENY);
const o2 = Services.scriptSecurityManager.createContentPrincipalFromOrigin('https://www.youtube.com');
Services.perms.addFromPrincipal(o2, 'cookie', Ci.nsICookiePermission.ACCESS_SESSION);

We don't have a way to do session cookie for specific sites via policies.

**Comment by cup** [comment]
> We don't have a way to do session cookie for specific sites via policies.

@mkaply this is confusing, as immediately before this sentence you include code that appears to do exactly that:

~~~js
const o2 = Services.scriptSecurityManager.createContentPrincipalFromOrigin('https://www.youtube.com');
Services.perms.addFromPrincipal(o2, 'cookie', Ci.nsICookiePermission.ACCESS_SESSION);
~~~

**Comment by mkaply** [comment]
I said via it doesn't work via policies (as in using our policy engine, GPO, policies.json).

I was giving you code to do it the old way - I'm guessing you were using autoconfig.

**Comment by mkaply** [comment]
FYI, we added session cookies into policy, so this can be done there.

I also updated the cookie setting so they are more clear (the new Behavior option)
