### ISSUE TITLE
enable-deprecated allows enabling protocols lower than locked min

### ISSUE THREAD

**Issue by mimi89999** [mozilla/policy-templates#541]
Hello,

After setting `SSLVersionMin` (`security.tls.version.min`) to `3` in GPO, when users are visiting websites that only support TLSv1.0 and TLSv1.1, they are presented a big blue button to enable TLSv1.0 and TLSv1.1. If they click it, `security.tls.version.enable-deprecated` will be changed to `true`.

This shouldn't be possible. If `security.tls.version.min` is set to a value and locked, enabling lower TLS versions shouldn't be recommended to users. It would be best if enabling lower protocols was completely blocked.
![Screenshot_win10_2020-03-01_16:12:04](https://user-images.githubusercontent.com/8530546/75628269-9ab6f800-5bd7-11ea-8d6b-2b36032e1b15.png)
![Screenshot_win10_2020-03-01_16:12:15](https://user-images.githubusercontent.com/8530546/75628270-9be82500-5bd7-11ea-9a54-6527d414a52d.png)
After selecting _Enable TLSv1.0 and TLSv1.1_:
![Screenshot_win10_2020-03-01_16:12:40](https://user-images.githubusercontent.com/8530546/75628271-9be82500-5bd7-11ea-8cc0-5a0208c500e1.png)

**Comment by mkaply** [comment]
This has been fixed in the latest beta and will be in the release next week.

https://bugzilla.mozilla.org/show_bug.cgi?id=1617275

**Comment by Poeggi** [comment]
This bug is not fixed, please reopen.

Verified with 92.0.1

**Comment by mimi89999** [comment]
@Poeggi Could you please provide more details? I couldn't reproduce it.

**Comment by Poeggi** [comment]
I am using Firefox 92.0.1 (64-Bit) on a fully patched (and updated to latest version) Windows 10, joined to a company domain.

We have rolled out a minimum TLS version via GPO (ADMX v3.1 installed on the DC).

I can see the GPO getting applied because the respective option on Firefox (about:config) is set and greyed out:
![grafik](https://user-images.githubusercontent.com/48416618/134782751-29a43e74-b147-4294-be51-a41ea44aae2a.png)

However, as soon as "enable-deprecated" gets set to "true", testing browsers supported TLS version via [1] will show TLS1.0 being supported.

Hope this helps reproducing the issue.

As a workaround, I am now also rolling out "enable-deprecated" via properties GPO (JSON). But it is really unintutive that we have to do this. IMO "version.min" should ALWAYS be adhered to.

[1]
https://browserleaks.com/ssl

**Comment by mimi89999** [comment]
OK. I understand now. Firefox no longer proposes to enable TLS 1.0 and 1.1, but it's still possible to enable them by setting `security.tls.version.enable-deprecated`.

Do you know any ways in which it might get set besides setting it in `about:config`?

**Comment by Poeggi** [comment]
In my case, it was already set before rolling out the Minimum TLS via GPO, effectively rendering the minimum TLS setting useless.

This is how I stumbled over it. So I believe there are many installations out there prone to getting caught by this.

Only sane solution is to enforce minimum TLS version, no matter what the state of „enable deprecated“ is.

-- 
Hand crafted on a mobile - please excuse typos

**Comment by mkaply** [comment]
So there are two ways to solve this.

1. We could add code to ignore enable-deprecated in Firefox.
2. I could change policy to lock enable-deprecated to false when Minimum TLs is set to 1.2 or above.

I think 2 is easier...
