### ISSUE TITLE
Managed keys to support caching option

### ISSUE THREAD

**Issue by ygini** [mozilla/policy-templates#551]
Hello

Firefox have two config key dedicated to caching services: `browser.cache.memory.enable` and `browser.cache.disk.enable`.

Those two settings are enabled by default and cause issue with solution like vSphere (see https://kb.vmware.com/s/article/59696).

It could be great to have a way to disable those keys from management API.

Thanks a lot

**Comment by mkaply** [comment]
VMWare's suggesting to simply turn off caching is not really a good solution as it would negatively impact Firefox performance.

I'm reaching out to VMWare to see if we can help.

In the mean time, if you run vsphere in private browsing mode, it should solve this problem.

**Comment by LucvandenBerg** [comment]
In https://support.mozilla.org/en-US/questions/939338 there is written that one of those keys helps lowering the sizes of profiles. Since I have a large amount of Firefox users we would like to minimize the profile footprint. I know GitHub is not a support platform, but do any of you have experience lowering the profile sizes in enterprises? The audience on Firefox Policy-templates is a bit more Enterprise minded. If i'm not in the right place you can delete my question.

**Comment by mkaply** [comment]
First a reply to the original note:

I talked to VMWare and they fixed this. The change should not be necessary anymore.

For the second question:

I don't recommend turning off cache. But you can use policy to just clear the cache every time the browser is closed. That would be the best way to keep the size of profiles down:

https://github.com/mozilla/policy-templates/blob/master/README.md#sanitizeonshutdown-selective
