### ISSUE TITLE
Restore from previous session

### ISSUE THREAD

**Issue by ranjithckm7** [mozilla/policy-templates#584]
I'm trying to make "Restore from previous session" usable for end users, But i don't know which GPO/Config is making to grey out. Attached firefox.adml for your reference.
![image](https://user-images.githubusercontent.com/50207308/79855062-0fdcc780-83e8-11ea-8f95-83368f77a84c.png)

**Comment by ranjithckm7** [comment]
Update : I'm able to access "Restore previous session" from Menu But the same option is greyed out at Menu->Options->General->Start up.

**Comment by mkaply** [comment]
That happens if the Homepage GPO is locked (because Startpage is part of homepage)

**Comment by ranjithckm7** [comment]
> That happens if the Homepage GPO is locked (because Startpage is part of homepage)

Thank you so much for your response.

Addition to this scenario, I have created a user.js which consists of user_pref("browser.sessionstore.resume_session_once", true);

But the same isn't reflecting in about:config->browser.sessionstore.resume_session_once and it still shows as "false"

**Comment by mkaply** [comment]
That's not how that preference works. That's an internal preference we use to determine when we need to do a single resume of a session. We reset that manually when we do the resume.

**Comment by ranjithckm7** [comment]
Thanks @mkaply for your valuable response. :) Stay Safe.

**Comment by DuncanLithgow** [comment]
I'm a user with the problem @ranjithckm7 describes. I would like this issue reopened.

I don't understand why the homepage policy and restore tabs settings are connected. Can they be separated? It would be great if a policy set home page is just always loaded as the outer tab (this is how chrome and edge seem to be dealing with this organisation policy)

Is there any special rationale for these things being locked together?

**Comment by mkaply** [comment]
They are connected because the "restore tabs" option is one of the startpage options (as it is designed today in Firefox)

You can see that here:

https://searchfox.org/mozilla-central/rev/41c3ea3ee8eab9ce7b82932257cb80b703cbba67/browser/components/enterprisepolicies/Policies.jsm#1041

So is the goal here to have users be able to choose whether or not they restore the session or not but still have a homepage that is locked?

**Comment by DuncanLithgow** [comment]
i just think that pinned tabs, home pages, and restored tabs should not need to be in conflict. if there is a homepage set that that can just be loaded like any other (restored or pinned) tab. if it's been closed during the session then just re add it.

**Comment by mkaply** [comment]
Unfortunately they are in conflict (and the behavior is consistent across browsers).

Browsers also consider homepage and start page to be two different things (homepage being what you click when you click home)

Given that I can't make the change you're requesting, is there something else you're looking for?

**Comment by DuncanLithgow** [comment]
You are right that the behavior is consistent across browsers. I checked and my memory was incorrect.
I've confused 'startpage' and 'homepage' a few times, sorry, I haven't used either concept for years in my workflow.

I guess I'm just looking for an indication if there is merit in what I'm saying about separating these things (although it might not be possible now and may be difficult to implement in the future). Maybe this bug tracker for policy templates is no longer the relevant place for this discussion since you've said this can't be done with the current implementation.

Is what I'm asking for in some way obviously a bad idea - or is there a forum where it would make sense to discuss it further?

**Comment by mkaply** [comment]
You could open a bug in bugzilla.mozilla.org with exactly what you are requesting.

The main thing I can do in policy is still allow startpage to be changed (turn on or off restore previous sessions) even though the homepage is locked.

**Comment by DuncanLithgow** [comment]
would that change in policy be a meaningful problem? I guess the placement of the policy startpage tab would need to be set and a check for it's presence might need to be added - but that must be doable?

is policy 90% of what's currently in the way?

**Comment by mkaply** [comment]
I would just add Locking as a separate thing to startpage. Not a big deal. I'll open a bug.

**Comment by DuncanLithgow** [comment]
please add a link here when the bug is created

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1635825

**Comment by MichaelWie** [comment]
Is there a GPO to deactivate the item "restore previous session"? Unfortunately I couldn't find anything about it in the policy_templates_v2.1.zip for ESR 78.1.
So is this currently only enforced when the homepage is blocked?

**Comment by mkaply** [comment]
Because of the way restore previous session works (It's tied to the setting of the homepage), there's no way to prevent it from being used except by locking the homepage using the previous pref.

**Comment by MichaelWie** [comment]
Ok I see. Thank you for your quick answer.
