### ISSUE TITLE
Feature Request - Simplify Policies for Normal User, disable Restores Settings

### ISSUE THREAD

**Issue by drankinatty** [mozilla/policy-templates#588]
This is a feature request related to policies. 

I understand the desire to thin out the normal user-settings to provide enterprise more control over the configuration and deployment of Firefox within organizations. But this works against the normal home user. Have you ever tried to explain how to create and install a policies.json file to your parents? Or walk your friend or aunt through the use of the group policy editor on windows? It is a showstopper.

With all the great new policies, it would be useful for the home user to have a simple way to disable policies altogether that would restore the full set of options to the settings dialog/pages so you can walk your mom though turning an option on or off again. The removal of access to various options and replacing them with policies -- while great for enterprise with an IT department is terrible for the normal user than downloads your browser at home.

A simple policy to disable policies and restore full options to the settings pages would provide an elegant solution to this problem.

**Comment by mkaply** [comment]
Policies aren't intended for home users.

What policies are set on your parents/friends computer?

**Comment by drlellinger** [comment]
Enterprise policies are set because organizations want to secure their business by enabling the polices. Most organisations do not enable policies to discriminate users so this would open the door to disable the whole use of enterprise policies. If you want to configure your parents computer, use a computer that does not come from the organisation you or your parent work for. I am not explaining why breaking the policies could lead to losing the job at the organisation
