### ISSUE TITLE
GPO wish - remaining CIS benchmarks items

### ISSUE THREAD

**Issue by rhandqkez07** [mozilla/policy-templates#659]
In our organisation we try to be compliant to the CIS benchmarks. 
https://www.cisecurity.org/cis-benchmarks/

The following settings are from these benchmarks and are non-default.
We still relay on cck2 to apply these settings.

When these settings are added to the GPO, every non-default item from the CIS benchmarks (if still present) can be set.

browser.ssl_override_behavior
privacy.donottrackheader.enabled
privacy.popups.disable_from_plugins
security.dialog_enable_delay
extensions.blocklist.interval, not sure if this one is still valid setting? "extensions.blocklist.enable" is in GPO

Also this one:
security.ocsp.require --> this already has an open issue #116 

![browser ssl_override_behavior](https://user-images.githubusercontent.com/68916588/89192141-3e03a300-d5a4-11ea-8281-d0b9c9f2a824.png)
![privacy donottrackheader enabled](https://user-images.githubusercontent.com/68916588/89192150-40fe9380-d5a4-11ea-9836-bc31cc026724.png)
![privacy popups disable_from_plugins](https://user-images.githubusercontent.com/68916588/89192157-4360ed80-d5a4-11ea-94a5-d30896a05e90.png)
![security dialog_enable_delay](https://user-images.githubusercontent.com/68916588/89192163-465bde00-d5a4-11ea-99b0-cccc83d05f36.png)
![extensions blocklist interval](https://user-images.githubusercontent.com/68916588/89192174-49ef6500-d5a4-11ea-8a60-b51d7efcbcd0.png)

**Comment by mkaply** [comment]
These recommendations are quite dated (Not updated in over five years).

Instead of browser.ssl_override_behavior, if you don't want users to add exceptions, you can use the DisableSecurityBypass policy.

As far as privacy.donottrackheader.enabled goes, the DNT header isn't honored by most sites and fell out of favor, so this isn't really a thing anymore.

privacy.popups.disable_from_plugins is already set to 3 to block all popups from plugins

security.dialog_enable_delay is set to 1 second which should be plenty of time to avoid issues (what do they recommend).

extensions.blocklist.interval should be unnecessary to change. The list is queried often enough.

**Comment by rhandqkez07** [comment]
Thanks for your response, that's really helpful.
