### ISSUE TITLE
DisableDefaultBrowserAgent

### ISSUE THREAD

**Issue by pilgi3** [mozilla/policy-templates#698]
[https://github.com/mozilla/policy-templates#disabledefaultbrowseragent](url)
Could somebody explain what this GPO setting does?

Because we discovered the new scheduled task (since Firefox 75) "Firefox Default Browser Agent 308046B0AF4A39CB" and i thought with this setting we could disable or remove the scheduled task.
If we set this GPO the scheduled task get not touched and the config "default-browser-agent.enabled" is still set to "true".

Thanks!

**Comment by mkaply** [comment]
Here's info from the install team:

The policy doesn't remove the task or prevent it from being installed, it just causes it to exit without doing anything. And the pref is separate from the policy (policy doesn't force the pref, the agent checks both)

If you manually remove the task and set the policy it shouldn't be readded

And rather than manually removing it, there's also the /RegisterDefaultAgent=false switch (and corresponding INI setting) for the installer.

Installing with /RegisterDefaultAgent=false should be all that's needed, as we record that in the registry so the agent never gets installed on a subsequent update. Probably not a bad idea to set the policy anyway just in case, but not necessary.

**Comment by pilgi3** [comment]
Thank you so much for the detailed explanation!
It's good to know about the mechanism.

We are using the MSI installer and added the parameter right now. Our clients get updated by PatchMyPC. They use the EXE installer but we added the parameter as well.
