### ISSUE TITLE
GPO REQ: HTTPS only configuration

### ISSUE THREAD

**Issue by chmichael** [mozilla/policy-templates#712]
Hello,
  Please add the new "HTTPS only" feature to the GPO Settings! (firefox 83 and up)

Thank you

**Comment by mkaply** [comment]
You can already set it via the new Preferences policy:

dom.security.https_only_mode
dom.security.https_only_mode_pbm

I'll investigate a separate policy though if Chrome has one.

**Comment by chmichael** [comment]
Hello,
  Where is it extactly i can not find it! (see screenshot)

Thank you
![firefox-GPO](https://user-images.githubusercontent.com/13120950/100283612-86413980-2f76-11eb-93e8-722d85ccf4d3.jpg)

**Comment by Schluggi** [comment]
It is also already available for the polices.json? I could not found it.

**Comment by mkaply** [comment]
There is a new policy called "Preferences" (not the category, top level policy)

https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

With it, you can set arbitrary preferences like these via JSON.

I checked Chrome and it doesn't appear to have a policy (yet) for turning this on/off.

**Comment by My1** [comment]
yes this is closed but this is still relevant, and a new issue would likely just get marked as duplicate.

wouldn't it make sense to have a proper setting for this tho, I mean if you could defer everything to preferences, you could just stop making policy objects completely and just have one big "preferences" policy, yeah no not ideal especially what happens if you have multiple GPOs applied that both supply a "Preferences" json (with neither containing any prefs that the others would contain) would they be properly merged or would only one set "win"?

**Comment by mkaply** [comment]
It's a tradeoff and I never know what the right thing to do is. It doesn't make sense to make policy for every preference (there would be too many).

And I do make new policies that sometimes correspond to prefs and sometimes don't. This one in particular has a policy on Chrome now, so it's probably worth adding a policy. I'll open a bugzilla bug.

As far as merging, nothing gets merged in individual policies (and that doesn't happen on Windows either. Multiple GPOs don't get merged)

**Comment by mkaply** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1739714

**Comment by My1** [comment]
> As far as merging, nothing gets merged in individual policies (and that doesn't happen on Windows either. Multiple GPOs don't get merged)

like you cannot really merge anything on things like "search enging google" vs "search engine yahoo" and "search engine bing" (fictional example, not sure if there's actually policies for those). these literally cannot coexist.

well on individual policies there isnt much to merge in the first place as it's usually one policy affecting one thing, however this "policies" json object is precisely the opposite, a blanket thing affecting a ton, so it's far more likely that a need arises to configure different things in different policies, like having a company wide start page but enforcing things like HTTPS or DoH only for certain parts, which would likely be a pain if you only had preferences.

also do you happen to know what's the exact thing about the deprecated prefs section? will individual prefs die someday in favor of the json (especially also as the individual prefs from deprecated must be cleared for the json to do anything)?

**Comment by mkaply** [comment]
I can certainly look into merging the Preferences policy between policies.json and GPO with GPO winning.

> also do you happen to know what's the exact thing about the deprecated prefs section? will individual prefs die someday in favor of the json (especially also as the individual prefs from deprecated must be cleared for the json to do anything)?

In most cases with policy, I don't tend to completely remove support for things since someone probably still uses it and I don't want to break thing.

The only prefs that can be set by the deprecated prefs section are those explicit prefs.

**Comment by My1** [comment]
with "Json Policies" I meant the "preferences" GPO that you throw one json in, you know the one mentioned above as the workaround for things that dont have an individual GPO yet, is that what you mean by "policies.json" or is that something entirely different?
also I just noticed by looking at the admx stuff directly that new "preferences" (like DoH) apparently are thrown into the "Firefox" Section, may I ask what's the difference between these new preferences and the old, "preferences (deprecated)" subfolder ones?

**Comment by mkaply** [comment]
Sorry, I misunderstood. There is no concept of combining multiple GPOs on Windows, so I'm not sure what you mean. I thought you meant combining policies.json and GPO.

I definitely plan to add enterprise policies where necessary. The Preferences policy is really only designed for setting more obscure preferences that people asked for.

> also I just noticed by looking at the admx stuff directly that new "preferences" (like DoH) apparently are thrown into the "Firefox" Section, may I ask what's the difference between these new preferences and the old, "preferences (deprecated)" subfolder ones?

So the old deprecated preferences method only allowed a preference to be set as a default preference. The reason I created the new method is because you can now set a default preferences, lock a preference, or set a user preference (similar to what you could do with Autoconfig). It also is more flexible for adding arbitrary preference prefixes.

DoH Used to be under Firefox, but I realized that putting lots of things in one setting doesn't work very well for Windows ADMX (because everything must have a value). So I moved DNS Over HTTPS to it's own top level category so each option could be set individually.

**Comment by My1** [comment]
> There is no concept of combining multiple GPOs on Windows, so I'm not sure what you mean

yeah that was what I knew so far (especially also since most settings were pretty atomic in nature meaning one policy sets one thing so there isnt much to merge in the first place, like an on/off switch for some things), what I meant is what happens if you made multiple policies that all used the preferences json-style policy to set different things to different OUs of users and computers, on single settings which often are only user and only computer usually the one that's most direct wins over any parents, so far so expected.

for normal settings that have individual policies obviously you can do such things (e.g. have a parent-OU based setting to regulate auto updates and a child-OU based setting for the start page). however if prefs would have to be in the preferences json-style GPO that would not really work because there is no merging of same-named GPOs.

although to be honest I am not really knowledgable with GPO design and many other things in enterprise IT (usually cooleagues do that, thank god), especially with non-Microsoft GPOs, might have as well been that programs can see all the GPOs that apply and how they do so and the program can then deal with it (which could have made merging for the json-style preferences policy possible)

also considering there are newer individual preference GPOs (like DoH or whatever) another interesting question would be how THOSE interacted with the json-style blanket preferences policy, because for deprecated policies it's directly mentioned how that all works (enable >0 deprecated one and json-style prefs wont work) but for the newer ones it isnt that abundantly clear.

also could the deprecated prefs be updated (if not somewhere already done) to match the modern design so there is one less style of policy making involved?

**Comment by mkaply** [comment]
> another interesting question would be how THOSE interacted with the json-style blanket preferences policy, because for deprecated policies it's directly mentioned how that all works (enable >0 deprecated one and json-style prefs wont work) but for the newer ones it isnt that abundantly clear.

I've basically said it's undefined. It's best not to mix them.

> also could the deprecated prefs be updated (if not somewhere already done) to match the modern design so there is one less style of policy making involved?

So the deprecated prefs can be set via the new design. I left them there for posterity.
