### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by folknor** [mozilla/policy-templates#729]
I have Firefox deployed in 4 different companies, and I just found out about these policy templates after being frustrated with the autoupdates.

However, the README does not explain things in a manner that I can understand, so I am unsure which settings to tweak, and how.

First of all, the README should mention `ADMX templates should be added to the X:\Windows\PolicyDefinitions directory.`, like https://support.mozilla.org/en-US/kb/customizing-firefox-using-group-policy-windows does. But it should be even more explicit, it should say `The downloaded ZIP file should be extracted to X:\Windows\PolicyDefinitions`.

Second, I have questions about these settings:
1. `AppAutoUpdate`, says `If set to true, application updates are installed without user approval.`, so does that mean that this settings is _more powerful_ than the standard Firefox autoupdate, which requires users to enter an admin (!) password to update Firefox? Does this setting mean that Firefox will autoupdate without me (as the administrator) ever logging in? If the answer is "no", which I hope and presume it is, then the text is so misleading I can't even handle it. `If set to false, application updates are downloaded but the user can choose when to install the update.` so if false, can the user also install updates without supplying the admin password?
2. `AppUpdateURL`, does this need to be changed, or can we just leave it? What is the default?
3. `Bookmarks` are these forcefully added to the users bookmarks (if needed) every time he opens the browser, or will they stay deleted if removed by the user?
4. `DisableAppUpdate` says `Turn off application updates.` - that sounds final. So then I can no longer update Firefox manually as administrator even? Wording matters, please be clear and explicit, and elaborate.
5. `DisableDefaultBrowserAgent` what is a "default browser agent"? How is it different from the UserAgent string?
6. `PictureInPicture` says `Enable or disable Picture-in-Picture as well as lock it.`, but what does "lock it" mean? Lock the PIP button in place, lock the preference so that if I disable PIP the user can't override me?

But of course with a little testing and Googling I figured it out - I just wanted to report this here so that it can be improved for future users.

Thank you!

**Comment by mkaply** [comment]
> 
> 
> I have Firefox deployed in 4 different companies, and I just found out about these policy templates after being frustrated with the autoupdates.

I'm sorry you had trouble finding it. We've done everything we can to publicize this. If you search on Firefox group policy on google, you get these pages as the first hit.

> 
> However, the README does not explain things in a manner that I can understand, so I am unsure which settings to tweak, and how.
> 
> First of all, the README should mention `ADMX templates should be added to the X:\Windows\PolicyDefinitions directory.`, like https://support.mozilla.org/en-US/kb/customizing-firefox-using-group-policy-windows does. But it should be even more explicit, it should say `The downloaded ZIP file should be extracted to X:\Windows\PolicyDefinitions`.

This is only true for local group policy and not true for how ADMX templates are deployed in other situations (Active Directory). My assumption is that Windows administrators will be familiar with what to do with ADMX templates since very other application uses them.


> 
> Second, I have questions about these settings:
> 
>     1. `AppAutoUpdate`, says `If set to true, application updates are installed without user approval.`, so does that mean that this settings is _more powerful_ than the standard Firefox autoupdate, which requires users to enter an admin (!) password to update Firefox? Does this setting mean that Firefox will autoupdate without me (as the administrator) ever logging in? If the answer is "no", which I hope and presume it is, then the text is so misleading I can't even handle it. `If set to false, application updates are downloaded but the user can choose when to install the update.` so if false, can the user also install updates without supplying the admin password?

Users should not have to enter the admin password to get Firefox updates if the maintenance service is used. Once the service has been given admin permission, it will do the updates without user intervention.

If the user doesn't have permission then an admin password will be needed regardless of the policy settings. The policy can't override windows UAC. 

> 
>     2. `AppUpdateURL`, does this need to be changed, or can we just leave it? What is the default?

Only if you are doing a custom update URL. I'll update the docs.,

> 
>     3. `Bookmarks` are these forcefully added to the users bookmarks (if needed) every time he opens the browser, or will they stay deleted if removed by the user?

No, the bookmarks policy doesn't readd bookmarks if they are deleted. There was no easy way to implement that in Firefox. The bookmarks are deleted/readded if you change the policy.

I recommend using our new ManagedBookmarks policy which gives you more control and works more like chrome. 



>     4. `DisableAppUpdate` says `Turn off application updates.` - that sounds final. So then I can no longer update Firefox manually as administrator even? Wording matters, please be clear and explicit, and elaborate.

No, it just turns off Firefox updating itself. We can't prevent other update mechanisms. I'll update the docs.

> 
>     5. `DisableDefaultBrowserAgent` what is a "default browser agent"? How is it different from the UserAgent string?

You can read more about it here:

https://firefox-source-docs.mozilla.org/toolkit/mozapps/defaultagent/default-browser-agent/index.html

I'll add this link to the docs.

> 
>     6. `PictureInPicture` says `Enable or disable Picture-in-Picture as well as lock it.`, but what does "lock it" mean? Lock the PIP button in place, lock the preference so that if I disable PIP the user can't override me?

That's correct. I'll update the docs.

> 
> 
> But of course with a little testing and Googling I figured it out - I just wanted to report this here so that it can be improved for future users.
> 
> Thank you!

I'm glad you were able to figure it out.

We're a very small team working on this, so all feedback is appreciated.
