### ISSUE TITLE
Gdata antivirus overwrite firefox policies ?

### ISSUE THREAD

**Issue by florentlagoda** [mozilla/policy-templates#747]
Hi,
We use Gdata antivirus and it's web protection module who automatically add on all web browser.
But on Firefox if i go to the about:policies i don't see my policies what i put on Program Files\Mozilla Firefox\distribution\policies.json.
I see only Gdata webprotection :(
See my screenshot
How can i resolve this ?
![Capture d’écran_2021-03-19_12-05-15](https://user-images.githubusercontent.com/28236550/111771342-d6d4fd80-88ab-11eb-9213-6d0510ab94ed.png)

**Comment by mkaply** [comment]
This will be fixed in the new version of Firefox that will be released next week. Going forward, we will combine GPO and policies.json (with GPO Winning)

You can fix this locally by moving information from the registry:

HKEY_CURRENT_USER\SOFTWARE\Policies\Mozilla\Firefox
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Mozilla\Firefox

into your policies.json.

**Comment by florentlagoda** [comment]
Thanks i's ok with version 87.0

**Comment by mkaply** [comment]
Awesome!
