### ISSUE TITLE
Do Not Track

### ISSUE THREAD

**Issue by chebourne** [mozilla/policy-templates#827]
I searched but could find nothing regarding the 'Do Not Track' setting - has anything been implemented or planned for this setting?

**Comment by jwalawski** [comment]
Regarding tracking in general there are [EnableTrackingProtection](https://github.com/mozilla/policy-templates#enabletrackingprotection) and [Cookies (RejectTracker)](https://github.com/mozilla/policy-templates#cookies) policies. 

[Preferences](https://github.com/mozilla/policy-templates#preferences) policy unfortunately doesn't support "privacy." prefix. which could be used to set `privacy.donottrackheader.enabled`. If I were you, I would rather skip Do Not Track settings since it seems to be ignored by servers. 

[Global Privacy Control](https://blog.mozilla.org/netpolicy/2021/10/28/implementing-global-privacy-control/) might be more useful when it's fully implemented but for now you need to use [Autoconfig](https://support.mozilla.org/en-US/kb/customizing-firefox-using-autoconfig) and it is only available in Firefox Nightly.

**Comment by mkaply** [comment]
Yeah, Do Not Track never really took off, so I never added it to policy.
