### ISSUE TITLE
ESR Policies

### ISSUE THREAD

**Issue by MichiFr** [mozilla/policy-templates#83]
Hi,
this is a plea to make some if not all ESR policies available for the RR (rapid release) branch, too.

Background: I'm running an Active Directory (based on Samba on my Synology NAS) at home and would like to use frequent Firefox updates as well as those GPOs. Some of those ESR policies are quite useful for RR, too.

On the first run I would need at least those GPOs:

- DisableSystemAddonUpdate
- DisableTelemetry 
- Extensions 
- Homepage 
- OverrideFirstRunPage 
- OverridePostUpdatePage 
- SearchBar 
- WebsiteFilter 
- Search Engines

Thanks,
Michael

**Comment by mkaply** [comment]
I am investigating making these policies available if you are connected to an Active Directory server, similar to what Chrome does.

Unfortunately because these can be used for hijacking, we don't want them widely available.

**Comment by bp88** [comment]
@mkaply This is a very limited view on things. Windows and Active Directory are not the only types of environments where Firefox is used in. There are environments where AD does not exist and there are two other OS platforms that Firefox runs on: macOS and Linux.

As an enterprise IT admin who manages Macs, I would not be able to make use of the new enterprise support policy engine because we don't deploy Firefox ESR and don't have AD.

I was really encouraged that Mozilla was going to learn from its past and start introducing features for enterprise users. You mentioned Chrome for guidance on what you want to achieve. I hope you realize that Google Chrome policies are enforced regardless of what version of Chrome is running or whether AD is running on.

I have to say this response is quite disappointing to hear from Mozilla and the reasoning is based on complete FUD. Hijacking is always a possibility. There's nothing stopping someone from installing a hijacked version of Firefox ESR on someone's computer if we were to go with your argument.

I respectfully ask that Mozilla reconsider their stance on this and make enterprise policy support available on all versions of Firefox.

**Comment by mkaply** [comment]
This was a poor answer on my part and I apologize for that.

Similar to Chrome, on Mac and Linux we will make all policies available on RR and ESR. The only reason I didn't do it for Firefox 60 is I didn't have the code ready on Windows to only allow certain policies when Active Directory is present and I didn't want to have a half done implementation. I should have put more energy into getting the Windows Active Directory code working.

And for the record, Chrome does only allow certain policies on Windows only when connected to an Active Directory server. When they switched back to using the registry away from using the GPO/AD APIs, they added this restriction.

So to summarize, in Firefox 61, Mac and Linux will be unrestricted on rapid release. I hope to have the Windows Active Directory check done by then. If I don't it will continue to be restricted. Although I plan to make less policies on Windows enterprise only.

As far as hijacking goes it absolutely is a huge problem on Windows for Chrome and Firefox. And because we use the registry to read policies, it would be incredibly easy to hijack that way (far easier than any other mechanism). So it does make sense to limit reading policy on Windows only when connected to Active Directory. I guess an alternative might be to only allow policy on Windows Pro? I'll have to think about that.

As a side note, I'm also investigating support policy properly on Mac too.

**Comment by Ulyssys** [comment]
@mkaply 

I know this is probably still a work in progress, but I am not sure where else to ask:

Is it intended that the "SearchEngines" policy remain ESR-only? The organization I am deploying Firefox for is moving from ESR to RR channel to keep up with the latest changes, and this is one of the policies we configure to prevent tampering by users or websites.

**Comment by Ulyssys** [comment]
@mkaply

I know this is probably still a work in progress, but I am not sure where else to ask:

Is it intended that the "SearchEngines" policy remain ESR-only? The organization I am deploying Firefox for is moving from ESR to RR channel to keep up with the latest changes, and this is one of the policies we configure to prevent tampering by users or websites.

**Comment by mkaply** [comment]
What specifically do you change in the search policy?

What platform are you on? Do you use GPO?

**Comment by Ulyssys** [comment]
@mkaply 

For this it is a Windows Active Directory domain, using group policy templates from [release v1.8](https://github.com/mozilla/policy-templates/releases/tag/v1.8).

At the moment, we are only using the [Prevent Search Engine Installs](https://github.com/mozilla/policy-templates/blob/master/README.md#searchengines--preventinstalls) policy, set to enabled.

In the future we may also set/lock a default search engine or remove other built-in ones.
