### ISSUE TITLE
Add policy for: firefox view icon. and bookmark bar on new tab

### ISSUE THREAD

**Issue by Solwayuk** [mozilla/policy-templates#964]
Add a policy for the following:

**firefox view icon (enable/disable)** 
browser.tabs.firefox-view (true/false)

**bookmark bar > only show on new tab (enable/disable)**

**Comment by mkaply** [comment]
> Add a policy for the following:
> 
> **firefox view icon (enable/disable)** browser.tabs.firefox-view (true/false)

This can be set via the Preferences policy. I'm not going to add an explicit policy at this time for Firefox View

Firefox View itself honors policy (if sync is disabled, the sync features don't show).

> **bookmark bar > only show on new tab (enable/disable)**

This can also be set via Preferences:

browser.toolbars.bookmarks.visibility

// "newtab": Show on the New Tab Page
// "always": Always show
// "never": Never show

But I agree that since we already have a BookmarksToolbar policy, I should update the policy to include this.

I opened a bug for that:

https://bugzilla.mozilla.org/show_bug.cgi?id=1797527
